### ISSUE TITLE
Question about supported CSPs and interaction structure

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cm-ant#10]
안녕하세요. 올해 v0.3.0 릴리스 관련하여 문의 사항이 있습니다.
@hippo-an @MZC-CSC 

1) 목표 클라우드 인프라 전환 비용 검증 및 예측 개발/통합 시험 (v0.3.0 릴리스 대상)
* PRICE 관련
  * Price 관련 기능 제공 CSPs 대상을 문의 드립니다. 
  * CM-Beetle이 목표 인프라 생성 전/후, 해당 인프라에 매칭이되는 Price 정보를 찾아서 노출시켜주셔야 할 것 같은데, 어떤 방안을 가지고 계신지 궁금하며, 현재 처리 현황도 궁금합니다.

* COST 관련
  * 1종 클라우드: AWS 지원 예정이신 것이 맞나요?
  * 내부적으로 CB-Spider의 anycall 방식을 활용하시기로 한 것으로 알고 있는데, Cloud-Migrator 전체 구조 차원에서 해당 기능이 어느 서브시스템을 통해서 어떤 방식으로 노출이 되는 것을 고려하고 계신지 궁금합니다.

(cc @yunkon-kim @powerkimhub )

**Comment by hippo-an** [comment]
안녕하세요!
문의 사항에 대한 응답을 드리도록 하겠습니다.

---

Price 관련

**1.1. Price 관련 기능 제공 CSP**
price 관련 기능 제공 CSP 는 현재 Spider 의 priceinfo api 가 제공하는 CSP 에 대해서 모두 제공을 목표로 하고 있습니다.
다만, 1) 가격 조회에 connection 이 필요하고 2) csp 의 credential 에 적절한 IAM 권한 혹은 3) Billing Account 관련된 권한이 포함 되어야 가격 정보를 조회할 수 있습니다.
필요한 credential 과 적절한 권한이 없다면 price 정보 제공이 되지 않을 수 있습니다.

이부분에 대해선 price 정보 조회에 필요한 사용자 가이드를 제공하는 것으로 워크샵에서 말씀드렸습니다.


**1.2. 방안 및 처리 현황**
목표 인프라를 생성 **'전'** beetle 이 제공하는 목표 인프라 최적 형상 추천 스펙으로 ant price api 를 호출하여 **한 달 가격을 제공하는 것을 목표**하고 있습니다. (참고로, 별도로 시간당 인프라 가격을 제공하는 API는 제공하지 않지만 한 달 가격의 리턴 값에 spider의 시간 당 가격을 포함하고 있기는 합니다.)
현재 처리 현황은 사용자가 api 요청이 들어왔을 경우 spider priceinfo api 를 이용해서 처리하고 있습니다.

목표 인프라 생성 **'후'** Price에 대한 질문이 만약, 생성된 인프라에서 일정 기간 운영된 Cost 정보에 대한 질문이라면 아래 Cost 기능을 이용할 예정입니다.


---

Cost 관련
2.1. 지원 예정
- 네. 현재는 cost 정보에 대해서 1종 aws 에 대한 지원을 우선 목표로하고 있습니다.

2.2. 호출 시스템
spider 에 대한 직접 요청이 아닌 tumblebug 을 통한 post forwarding 방식으로 생각하고 있으며, spider 의 anycall 은 post 엔드포인트만 제공하는 것으로 확인했습니다.

tumblebug 은 spider 에 대한 request forwarding 을 GET 요청에 대해서만 지원하고 있는것으로 파악했으며,   
beetle 은 인프라 마이그레이션 실행 및 제어 부분에 대해 tumblebug api 를 감싸서 제공할 것으로 파악했습니다.

ant 는 tumblebug 에 대한 의존성만 있는 것을 고려했습니다.


그리고, **spider의 priceinfo api 에 대해서는 GET 엔드포인트가 존재하기 때문에 tumblebug 을 통한 호출이 가능하지만 tumblebug 차원에서 별도로 제공 해주실지도 결정이 필요할 것 같습니다.**

**Comment by seokho-son** [comment]
@hippo-an 우문/현답. 감사합니다. 처리 방안 및 목표, 확인하였습니다. :)

**Comment by hippo-an** [comment]
https://github.com/cloud-barista/cloud-migrator/issues/11#issuecomment-2283209196

테스트 및 지원 예정 CSP 에 대한 상세 정보는 해당 이슈를 참고 바랍니다.
